#!/bin/bash
# chkconfig: 2345 66 36
# /etc/rc.d/init.d/opt/python
# description: spython
#
case "$1" in
  start)
        echo "listen_net serive is start..."
        nohup python /tem/listen_netstat.py &
  stop)
        echo -n "Shutting Down python Listeners: "
        echo "---------------------------------------------------------------------------------" >>/var/log/python
        date +"! %T %a %D : Shutting Down python." >>/var/log/python
        echo "---------------------------------------------------------------------------------" >>/var/log/python
	echo "python"
        killall -9 listen_netstat.py
        echo "Done."
        echo "Done."
        echo "---------------------------------------------------------------------------------" >>/var/log/python
        date +"! %T %a %D : Finished." >>/var/log/python
        echo "---------------------------------------------------------------------------------" >>/var/log/python
        ;;
  *)
  echo "Usage: python { start | stop }"
  exit 1
esac
exit 0